require: rubocop-rails

AllCops:
  # TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
Style/AsciiComments:
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false